server:
  port: 8081
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tg
    username: postgres
    password: postgres
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin